EXCLUDED_WORDS = {'Exam', 'Intermediate', 'Guide', 'Project', 'Level', 'Functional', 'Content', 'Support', 'Professional', 'by', 'Streams', 'Framework', 'Portal', 'Language', '10', '2019', '2020', '2021', '2022', '2023', 'Programming', 'Application', '&', 'Using', 'Working', 'Environment', 'The', 'Way', 'Build', 'Part', 'a', 'an', 'and', 'of', 'the', 'to',
                  'with', 'With', 'Building', 'A', 'Applications', 'App', 'Market', 'Software', 'Advanced', 'Parallel', 'Coding', 'Web', '1', '2', '3', 'Learning', 'Introduction', 'Development', 'in', '-', 'Server', 'Studio', 'Practice', 'your', 'for', 'using', 'from', ' ', '', 'on', 'us', 'Visualization', 'Master', 'Performance'}

CATEGORIES = {
    "Software Development": ["developer", "db", "dba", "containers", "database", "databases", "koder", "testing", "tester", "development", "microservices", "blockchain", "software development", "web development", "mobile development", "user experience", "ui", "ux", "software engineering", "linux", "software architecture", "agile development", "version control", "software testing", "html", "django", "javascript", "node.js", "sun", "react", "angular", "java", "api"],
    "Data Analytics": ["analytics", "pytorch", "neural network", "neural networks", "process mining", "watson", "tensorflow", "automation", "data science", "ai", "big data", "cognos", "data analysis", "data mining", "data visualization", "statistics", "machine learning", "artificial intelligence", "predictive modeling", "data", "analysis", "r", "deep learning"],
    "Project Management": ["pmp", "mentor", "itil", "executive", "scrum", "project planning", "project control", "project management", "time management", "risk management", "resource management", "agile methodologies", "project lifecycle", "agile", "stakeholder management", "scrum Master", "product owner", "project manager"],
    "Cybersecurity": ["hacker", "hack", "cybersecurity", "network", "security", "cryptography", "data protection", "security auditing", "incident response", "ethical hacking", "information security", "penetration testing"],
    "Cloud Computing": ["aws", "azure", "cloud computing", "cloudant", "infrastructure as a service", "virtualization", "platform as a service", "cloud architecture", "cloud", "cloud deployment", "kubernetes", "devops"],
    "Mainframe and Systems": ["mainframe", "systems administrator", "systems administration", "performance optimization", "legacy systems", "server virtualization", "system architecture", "system maintenance", "troubleshooting"]
}
